// Generated by https://quicktype.io

export interface IHistory {
  data: Datum[];
}

export interface Datum {
  messageId:                 string;
  messageSentAt:             string;
  messageExecutionStartedAt: string;
  messageExecutedAt:         string;
  createdAt:                 string;
  updatedAt:                 string;
}

