// Generated by https://quicktype.io

export interface IHistoryP {
  data: DatumP[];
}

export interface DatumP {
  messageId:                 string;
  messageSentAt:             string;
  messageExecutionStartedAt: string;
  messageExecutedAt:         string;
  createdAt:                 string;
  updatedAt:                 string;
}

