// Generated by https://quicktype.io

export interface IHistoryE {
  data: DatumE[];
}

export interface DatumE {
  messageId:                 string;
  messageSentAt:             string;
  messageExecutionStartedAt: string;
  messageExecutedAt:         string;
  createdAt:                 string;
  updatedAt:                 string;
  time:                 string;
}

